name: Pull Request Validation

on:
  workflow_call:
    inputs:
      types:
        description: 'Allowed PR types'
        required: false
        default: |
          fix
          feat
          ci
          chore
        type: string
      requireScope:
        description: 'Whether to require a scope'
        required: false
        default: false
        type: boolean

jobs:
  check-pr-title:
    name: Check Pull Request Title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          types: ${{ inputs.types }}
          requireScope: ${{ inputs.requireScope }} 