name: Readme Generator (Reusable)

on:
  workflow_call:
    inputs:
      readme_yaml:
        required: true
        type: string
      external_modules:
        required: true
        type: string
      output_path:
        required: false
        type: string
        default: README.md

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download reusable action content
        uses: actions/checkout@v3
        with:
          repository: gocloudLa/.github
          ref: feature/readme-generator # Remover esta ref finalizado el desarrollo
          path: .action-tmp
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .action-tmp/readme-templates/requirements.txt
      - name: Readme Generator
        run: |
          python .action-tmp/readme-templates/generate_readme.py \
            --yaml ${{ inputs.readme_yaml }} \
            --general .action-tmp/readme-templates/README.general.yaml \
            --template .action-tmp/readme-templates/README.md.gotmpl \
            --external ${{ inputs.external_modules }} \
            --output ${{ inputs.output_path }}
      - name: Commit README if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ${{ inputs.output_path }}
          git diff --cached --quiet || git commit -m "chore(doc): update README.md [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 