name: "Shared Terraform Pull Request Events"

on:
  workflow_call:
    inputs:
      workflow_ref:
        required: false
        type: string
        default: main
        description: "Branch or ref to use for workflow references"
      foo:
        required: false
        type: string
        default: bar

concurrency:
  group: shared-terraform-pull-request-events-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull-request-validation:
    # if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'edited' || github.event.action == 'reopened')
    uses: gocloudLa/.github/.github/workflows/pull-request-validation.yml@${{ inputs.workflow_ref }}
    secrets: inherit 
    # with:
    #   readme_yaml: ${{ inputs.readme_yaml }}
    #   output_path: ${{ inputs.output_path }}

  terraform-validation:
    # if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize')
    uses: gocloudLa/.github/.github/workflows/terraform-validation.yml@${{ inputs.workflow_ref }}
    secrets: inherit

  workflow-summary:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [ pull-request-validation, terraform-validation ]
    steps:
      - run: |
          echo '${{ toJSON(needs) }}'  # easier debug
          ! ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
