name: "Shared Terraform Pull Request Events"

on:
  workflow_call:
    inputs:
      foo:
        required: false
        type: string
        default: bar

concurrency:
  group: shared-terraform-pull-request-events-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull-request-validation:
    if: github.event_name == 'pull_request_target'
    uses: gocloudLa/.github/.github/workflows/pull-request-validation.yml@feature/readme-generator
    secrets: inherit 
    # with:
    #   readme_yaml: ${{ inputs.readme_yaml }}
    #   output_path: ${{ inputs.output_path }}

  terraform-validation:
    if: github.event_name == 'pull_request'
    uses: gocloudLa/.github/.github/workflows/terraform-validation.yml@feature/readme-generator
    secrets: inherit