name: General Maintenance (Reusable)

on:
  workflow_call:
    inputs:
      workflow_ref:
        required: false
        type: string
        default: main
        description: "Branch or ref to use for workflow references"
      foo:
        required: false
        type: string
        default: bar
      # output_path:
      #   required: false
      #   type: string
      #   default: README.md

jobs:
  general-maintenance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "latest"

      - name: Detect Terraform modules
        id: detect_modules
        run: |
          # Change to terraform directory and initialize
          echo "Maintenance Started !!"

      - name: Download reusable action content
        uses: actions/checkout@v4
        with:
          repository: gocloudLa/.github
          ref: ${{ inputs.workflow_ref }}
          path: ./shared-repository

      - name: Debug Files
        run: |
          pwd
          find ./shared-repository